<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Title>PleasantUI</Title>
        <PackageId>PleasantUI</PackageId>

        <IncludeBuildOutput>true</IncludeBuildOutput>
        <DevelopmentDependency>false</DevelopmentDependency>
    </PropertyGroup>

    <Import Project="..\..\build\Package.props" />

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Skia" Version="12.1.1" />
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <CompilerVisibleProperty Include="RootNamespace" />
        <CompilerVisibleProperty Include="AssemblyName" />
        <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
    </ItemGroup>
    
    <ItemGroup>
        <None Include="..\..\generators\PleasantUI.Localization.Generator\bin\$(Configuration)\netstandard2.0\PleasantUI.Localization.Generator.dll"
              Pack="true"
              PackagePath="analyzers\dotnet\cs"
              Visible="false" />
        <None Include="..\..\analyzers\PleasantUI.Localization.Analyzer\bin\$(Configuration)\netstandard2.0\PleasantUI.Localization.Analyzer.dll"
              Pack="true"
              PackagePath="analyzers\dotnet\cs"
              Visible="false" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="..\..\build\PleasantUI.Localization.Analyzer.targets">
            <Pack>true</Pack>
            <PackagePath>build\;buildTransitive\</PackagePath>
        </Content>
        <Content Include="..\..\build\PleasantUI.Localization.Generator.targets">
            <Pack>true</Pack>
            <PackagePath>build\;buildTransitive\</PackagePath>
        </Content>
    </ItemGroup>
</Project>
