<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DebugType>Full</DebugType>
        <IncludeAvaloniaGenerators>true</IncludeAvaloniaGenerators>
        <NeutralLanguage>en</NeutralLanguage>

        <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
        <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)generated</CompilerGeneratedFilesOutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugType>embedded</DebugType>
        <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\PleasantUI.DataGrid\PleasantUI.DataGrid.csproj"/>
        <ProjectReference Include="..\..\src\PleasantUI.ToolKit\PleasantUI.ToolKit.csproj"/>
        <ProjectReference Include="..\..\src\PleasantUI\PleasantUI.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\generators\PleasantUI.Localization.Generator\PleasantUI.Localization.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />

        <ProjectReference Include="..\..\analyzers\PleasantUI.Localization.Analyzer\PleasantUI.Localization.Analyzer.csproj"
                          IncludeAssets="runtime; build; native; contentfiles; analyzers"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Material.Icons.Avalonia" Version="3.0.2" />
        <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="5.3.0" />
        <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.1" PrivateAssets="All" />
    </ItemGroup>
    
    <ItemGroup>
        <AdditionalFiles Include="Properties\Localizations\*.resx"/>

        <AdditionalFiles Include="Properties\Localizations\Library.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Library.Designer.cs</LastGenOutput>
        </AdditionalFiles>

        <AdditionalFiles Include="Properties\Localizations\App.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>App.Designer.cs</LastGenOutput>
        </AdditionalFiles>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\Pages\PleasantControlPages\ProgressRingPageView.axaml.cs">
            <DependentUpon>ProgressRingPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Pages\ControlPages\ProgressBarPageView.axaml.cs">
            <DependentUpon>ProgressBarPageView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Properties\Localizations\App.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>App.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\Localizations\Library.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Library.resx</DependentUpon>
        </Compile>
    </ItemGroup>
</Project>
