//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PleasantUI.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PleasantUI.Example.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add color.
        /// </summary>
        public static string AddColor {
            get {
                return ResourceManager.GetString("AddColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your new color!.
        /// </summary>
        public static string AddYourNewColor {
            get {
                return ResourceManager.GetString("AddYourNewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chan_ge.
        /// </summary>
        public static string ChangeMenu {
            get {
                return ResourceManager.GetString("ChangeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string CloseMenu {
            get {
                return ResourceManager.GetString("CloseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ollapse.
        /// </summary>
        public static string CollapseMenu {
            get {
                return ResourceManager.GetString("CollapseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color wheel.
        /// </summary>
        public static string ColorWheel {
            get {
                return ResourceManager.GetString("ColorWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string CopyMenu {
            get {
                return ResourceManager.GetString("CopyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom themes.
        /// </summary>
        public static string CustomThemes {
            get {
                return ResourceManager.GetString("CustomThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_ut.
        /// </summary>
        public static string CutMenu {
            get {
                return ResourceManager.GetString("CutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Expand.
        /// </summary>
        public static string ExpandMenu {
            get {
                return ResourceManager.GetString("ExpandMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No custom themes.
        /// </summary>
        public static string NoCustomThemes {
            get {
                return ResourceManager.GetString("NoCustomThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string PasteMenu {
            get {
                return ResourceManager.GetString("PasteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restore.
        /// </summary>
        public static string ReestablishMenu {
            get {
                return ResourceManager.GetString("ReestablishMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved colors.
        /// </summary>
        public static string SavedColors {
            get {
                return ResourceManager.GetString("SavedColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme editor.
        /// </summary>
        public static string ThemeEditor {
            get {
                return ResourceManager.GetString("ThemeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color is copied to the clipboard.
        /// </summary>
        public static string ThemeEditor_ColorCopiedToClipboard {
            get {
                return ResourceManager.GetString("ThemeEditor/ColorCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy theme.
        /// </summary>
        public static string ThemeEditor_CopyTheme {
            get {
                return ResourceManager.GetString("ThemeEditor/CopyTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop the theme file here.
        /// </summary>
        public static string ThemeEditor_DragAndDropThemeHere {
            get {
                return ResourceManager.GetString("ThemeEditor/DragAndDropThemeHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export theme.
        /// </summary>
        public static string ThemeEditor_ExportTheme {
            get {
                return ResourceManager.GetString("ThemeEditor/ExportTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get colors based on....
        /// </summary>
        public static string ThemeEditor_GetColorsBasedOn {
            get {
                return ResourceManager.GetString("ThemeEditor/GetColorsBasedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import theme.
        /// </summary>
        public static string ThemeEditor_ImportTheme {
            get {
                return ResourceManager.GetString("ThemeEditor/ImportTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors installed.
        /// </summary>
        public static string ThemeEditor_NumberOfColorsInstalled {
            get {
                return ResourceManager.GetString("ThemeEditor/NumberOfColorsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste theme.
        /// </summary>
        public static string ThemeEditor_PasteTheme {
            get {
                return ResourceManager.GetString("ThemeEditor/PasteTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme copied to clipboard.
        /// </summary>
        public static string ThemeEditor_ThemeCopiedToClipboard {
            get {
                return ResourceManager.GetString("ThemeEditor/ThemeCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme has been successfully exported.
        /// </summary>
        public static string ThemeEditor_ThemeExported {
            get {
                return ResourceManager.GetString("ThemeEditor/ThemeExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme has been successfully imported.
        /// </summary>
        public static string ThemeEditor_ThemeImported {
            get {
                return ResourceManager.GetString("ThemeEditor/ThemeImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while importing the theme.
        /// </summary>
        public static string ThemeEditor_ThemeImportError {
            get {
                return ResourceManager.GetString("ThemeEditor/ThemeImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme name.
        /// </summary>
        public static string ThemeEditor_ThemeName {
            get {
                return ResourceManager.GetString("ThemeEditor/ThemeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
    }
}
