using System;
using System.IO;
using System.Net.Http;
using System.Text;
using Microsoft.CodeAnalysis;
using System.Text.Json.Nodes;
using System.Threading.Tasks;

namespace PleasantUI.MaterialIcons.SourceGenerator;

[Generator]
public class MaterialIconsSourceGenerator : IIncrementalGenerator
{
	const string MaterialIconsFetchApi = "https://dev.materialdesignicons.com/api/package/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B";

	private JsonNode? _json;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		using HttpClient httpClient = new();

		Task<Stream> task = Task.Run(() => httpClient.GetStreamAsync(MaterialIconsFetchApi));
		task.Wait();
		
		Stream? dataStream = task.Result;
		JsonNode? json = JsonNode.Parse(dataStream);

		_json = json ?? throw new Exception("Unable to load JSON");
		
		if (_json is null)
			throw new NullReferenceException("JSON is null");
		
		JsonArray icons = _json.Root["icons"]!.AsArray();

		const string generated = """
		                         // <auto-generated/>
		                         using Avalonia.Media;

		                         namespace PleasantUI;

		                         public static partial class MaterialIcons
		                         {
		                         """;

		StringBuilder stringBuilder = new(generated);

		foreach (JsonNode? icon in icons)
		{
			string name = icon!["name"]!.GetValue<string>().Underscore().Pascalize();
			string data = icon["data"]!.GetValue<string>();
			
			stringBuilder.Append($"\tpublic static Geometry {name} = Geometry.Parse(\"{data}\");\n");
		}
		
		stringBuilder.Append("}\n");
		
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource("MaterialIcons.g.cs", stringBuilder.ToString()));
	}
}