using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace PleasantUI.Localization.Generator;

[Generator]
public class ResxLocalizationGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor FoundKeysDescriptor = new(
        "PUILOC001",
        "Localization keys found",
        "Source Generator found {0} unique localization keys from {1} .resx files",
        "Localization",
        DiagnosticSeverity.Info,
        true
    );

    private static readonly DiagnosticDescriptor NoResxFilesDescriptor = new(
        "PUILOC002",
        "No .resx files found",
        "No .resx files were found in the project. Source Generator did not generate LocKey enum.",
        "Localization",
        DiagnosticSeverity.Warning,
        true
    );

    private static readonly DiagnosticDescriptor ParsingErrorDescriptor = new(
        "PUILOC003",
        "Resx Parsing Error",
        "Failed to parse .resx file '{0}': {1}",
        "Localization",
        DiagnosticSeverity.Error,
        true
    );

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<string?> customSettingProvider = context.AnalyzerConfigOptionsProvider
            .Select((options, _) =>
                options.GlobalOptions.TryGetValue("build_property.PleasantUIDisableResxKeyGenerator", out string? value) ? value : null);

        IncrementalValuesProvider<AdditionalText> resxProvider = context.AdditionalTextsProvider
            .Where(static f => f.Path.EndsWith(".resx", StringComparison.OrdinalIgnoreCase));

        var resxWithContent = resxProvider.Select((file, _) =>
        {
            try
            {
                string content = file.GetText()?.ToString() ?? "";
                List<string> keys = ExtractKeys(content, file.Path);

                return (FilePath: file.Path, Keys: keys, Success: true, Error: null);
            }
            catch (Exception e)
            {
                return (FilePath: file.Path, Keys: new List<string>(), Success: false, Error: e.Message);
            }
        });

        var valueProvider = resxWithContent.Collect().Combine(customSettingProvider);

        context.RegisterSourceOutput(valueProvider, (spc, source) =>
        {
            var files = source.Left;
            string? settingValue = source.Right;

            if (string.Equals(settingValue, "true", StringComparison.OrdinalIgnoreCase))
                return;

            if (files.IsEmpty)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    NoResxFilesDescriptor,
                    Location.None));
                return;
            }

            HashSet<string> allKeys = [];
            int processedFiles = 0;

            foreach (var file in files)
            {
                if (!file.Success)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(ParsingErrorDescriptor,
                        Location.None,
                        file.FilePath,
                        file.Error ?? "Unknown error"));
                    
                    continue;
                }

                if (file.Keys.Count <= 0)
                    continue;

                processedFiles++;
                foreach (string key in file.Keys)
                    allKeys.Add(key);
            }

            if (allKeys.Count == 0)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    NoResxFilesDescriptor,
                    Location.None));

                return;
            }

            spc.ReportDiagnostic(Diagnostic.Create(
                FoundKeysDescriptor,
                Location.None,
                allKeys.Count,
                processedFiles));

            List<string> orderedKeys = allKeys.OrderBy(k => k).ToList();
            string sourceText = GenerateLockKeyEnum(orderedKeys, processedFiles);

            spc.AddSource("LocKey.g.cs", SourceText.From(sourceText, Encoding.UTF8));
        });
    }


    private static string GenerateLockKeyEnum(List<string> keys, int fileCount)
    {
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by PleasantUI.Localization.Generator");
        sb.AppendLine($"// {DateTime.Now:yyyy-MM-dd HH:mm:ss} from {fileCount} .resx file(s)");
        sb.AppendLine("// Do not modify this file manually.");

        sb.AppendLine("namespace PleasantUI.Core.Localization;");
        sb.AppendLine("");
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Strongly-typed localization keys generated from .resx files.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public enum LocKey");
        sb.AppendLine("{");

        foreach (string key in keys)
        {
            string safeName = SanitizeIdentifier(key);
            sb.AppendLine($"    {safeName}, // Original: {key}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static List<string> ExtractKeys(string content, string filePath)
    {
        List<string> keys = [];

        try
        {
            XDocument doc = XDocument.Parse(content);

            foreach (XElement element in doc.Descendants("data"))
            {
                string? name = element.Attribute("name")?.Value;
                if (!string.IsNullOrWhiteSpace(name))
                    keys.Add(name!);
            }
        }
        catch (Exception e)
        {
            throw new InvalidOperationException($"XML parsing failed for {filePath}", e);
        }

        return keys;
    }

    private static string SanitizeIdentifier(string name)
    {
        string sanitized = name
            .Replace("/", "__")
            .Replace("\\", "__")
            .Replace(".", "_")
            .Replace("-", "_");

        sanitized = Regex.Replace(sanitized, "[^a-zA-Z0-9_]", "_");

        if (char.IsDigit(sanitized[0]))
            sanitized = "_" + sanitized;

        return sanitized;
    }
}